[project]
name = "pandasutils"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cattrs",
    "pandas",
]
[project.optional-dependencies]
dev = [
  "pytest",           # 开发依赖
  "pytest-cov",       # 测试覆盖率工具
]
